name: Validate PR

on: [pull_request]

jobs:
  pull-request:
    name: Test Pull Request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint
    - name: Syntax Check
      run: |
        ansible-playbook -i inventory site.yml --syntax-check
    - name: Ansible lint
      run: |
        ansible-lint -v roles/netbootxyz
    - name: Run PR check
      run: |
        ./script/build_release pr
